name: DeployBlog# Actions名称
on:
  push: # 监听调用时机为push事件
    branches: ['docs']
jobs:
  build:
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    steps:
      - name: 拉取代码 # 步骤名字
        uses: actions/checkout@master # 使用 actions/checkout 库拉取最新源码

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: 项目安装依赖
        run: pnpm install --frozen-lockfile

      - name: 项目打包构建
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: pnpm build

      - name: 部署产物到服务器
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: 'docs/.vitepress/dist/'
          target: '/${{secrets.SSH_USERNAME}}/Projects/.tianjie_temp/'
          rm: true
          strip_components: 3

      - name: 执行远程脚本命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /${{secrets.SSH_USERNAME}}/Projects/tianjie-docs/*
            cp -rf /${{secrets.SSH_USERNAME}}/Projects/.tianjie_temp/*  /${{secrets.SSH_USERNAME}}/Projects/tianjie-docs/
      - run: echo "项目部署完成！"
